/**
 * A js file that contains english transulation for the UI.
 */
var Lang = {
    dir:'ltr',
    'lang-name':'English',
    'code':'en',
    Actions:{
        'publish':'Publish',
        'publish-updates':'Publish Updates',
        'add':'Add',
        'activate':'Activate Account',
        'add-user':'Add User',
        'add-list-item':'Add List Item',
        'add-section':'Add Section',
        'login':'Login',
        'save':'Save',
        'remove':'Remove',
        'cancel':'Cancel',
        'edit':'Edit',
        'next':'Next',
        'prev':'Previous',
        'preview':'Preview',
        'check':'Check',
        'run-setup':'Run Setup',
        'done':'Done',
        'view-pages':'View Pages',
        'add-paragraph':'Paragraph',
        'add-list':'List',
        'add-html':'HTML Code',
        'add-code':'Code',
        'add-image':'Image',
        'add-sub-sec':'Section'
    },
    Status:{
        'invalid-html':'Invalid HTML Code!',
        'connected':'Connected!',
        'publishing':'Publishing Content...',
        'no-groups':'No Groups',
        'no-pages':'No Pages',
        'adding-user':'Adding New User...',
        'saving':'Saving...',
        'loading':'Loading...',
        'removing':'Removing...',
        'adding-group':'Adding new group...',
        'adding-page':'Adding new page...',
        'wait':'Please wait a moment...',
        'account-created':'New account is created!',
        'success':'Success!',
        'setup-completed':'Setup is Completed!'
    },
    Errs:{
        'login':'Inncorect username or password!',
        'server-err':'Server Error!',
        'something-wrong':'Something went wrong, try again.',
        'not-allowed':'You are not allowed to do that.',
        'not-auth':'You don\'t have the permission to do that.',
        'lost-connection':'Unable to Connect. Check your Internet Connection.',
        'load-error':'Unable to load.',
        'save-error':'Unable to Save. Try Again.',
        'inv-group-title':'Invalid group title.',
        'inv-file-name':'Invalid file name!',
        'inv-parag-text':'Invalid paragraph text!',
        'inv-title':'Invalid page title!',
        'inv-desc':'Invalid page description!',
        'inv-req':'Invalid request!',
        'inv-tran':'Invalid transaction!',
        'pub-err':'Unable to publish. Try again.',
        'req-meth-not-supported':'Request method not supported.',
        'transactions-disabled':'Transactions with the server are disabled!',
        'groups-load-err':'Unable to get groups from the server!',
        'password-missmatch':'The given two passwords does not match!'
    },
    Langs:[
        {'name':'Arabic','code':'AR'},
        {'name':'English','code':'EN'}
    ],
    Placeholders:{
        'access-level':'Select user access level...',
        'db-host':'Type in atabase host name (e.g. 192.123.68.0 or www.example.com)',
        'db-user':'Type in database username.',
        'db-pass':'Type in database user password.',
        'db-name':'Type in database name.',
        'activate':'Please type in the activation token.',
        'admin-user':'Type in the admin username.',
        'general-text':'Type Somthing...',
        'username':'Type in the username.',
        'user-or-email':'Enter your username or email.',
        'password':'Enter account password.',
        'conf-pass':'Please enter the choosen password again.',
        'group-title':'Give a nice name for the group.',
        'page-title':'Give a descriptive title for the page.',
        'group-pub-dir':'A directory where group pages will be published to.',
        'group-res-dir':'A directory that will contain group resources such as images.',
        'page-lang':'Select page language.',
        'page-file-name':'The name of the file that the page will be published to.',
        'page-desc':'A short description for the page.',
        'page-group':'Select the group that the page will belongs to.',
        'section-title':'A title for the section that reflects its content.',
        'email':'Type in the account email address.'
    },
    ViewTitle:{
        'activate':'Entering User Activation Token',
        'admin-account-info':'Administrator Account Information:',
        'db-info':'Database Information:',
        'setup':'Setup The Content Management System',
        'list-item':'List Item',
        'edit':'Page Content',
        'page-lang':'Page Language:',
        'login':'Enter your credintials bellow',
        'add-group':'Group Information',
        'add-page':'Page Information',
        'page-title':'Page Title',
        'page-desc':'Page Description',
        'paragraph':'Paragraph',
        'section':'Section',
        'html':'HTML',
        'code':'Code',
        'ul':'Unordered List',
        'image':'Image',
        'add-user':'User Information:'
    },
    Labels:{
        'access-level':'User Access Level:',
        'db-host':'Host Name:',
        'username':'Username:',
        'db-name':'Database Name:',
        'user-or-email':'Email or username:',
        'password':'Password:',
        'conf-pass':'Confirm Password:',
        'email':'Email Address:',
        'list-item':'List Item',
        'author':'Author:',
        'title':'Title:',
        'pub-dir':'Publish Directory:',
        'res-dir':'Resources Directory:',
        'page-count':'Pages in Group:',
        'group':'Group:',
        'status':'Status:',
        'desc':'Description:',
        'date-created':'Date Created:',
        'date-pub':'Date Published:',
        'last-updated':'Last Updated:',
        'lang':'Language:',
        'file-name':'File Name:',
        'sec-body':'Section Content:',
        'add':'Add:'
    },
    Dialogs:{
        'remove-view':'Remove view? (No undo)',
        'remove-group':'Are you sure you would like to remove the group? (No undo)',
        'remove-page':'Are you sure you would like to remove the page? (No undo)'
    },
    Tooltips:{
        'hide-content':'Hide the content.',
        'show-content':'Show the content.'
    },
    SetupInstructions:{
        'database-info':'In here, we need from you to give us MySQL database information. \n\
                         We use the database to store the awsome content that you will create. <br/>\n\
                        The things that we need are: <b>Host Name</b>, <b>Username</b>, <b>Password</b> \n\
                        and <b>Database Name</b>.',
        'admin-account-info':'Now that your database is setup, we need from you to create an <b>Administrator Account</b>. \n\
        This account is used to manage all the main settings of the content management system. We need from you to provide a <b>Username</b>, \n\
        <b>Password</b> and an <b>Email Address</b>.<br/><br/> <em>Note that once you go beyond this step, you cannot go back.</em>'
    }
};