name: Build PHP 7

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }} 
    strategy: 
      fail-fast: true
      matrix: 
        os: [ ubuntu-latest ]
        php: [7.1, 7.0, 5.6]
            
    name: PHP${{matrix.php}} - ${{matrix.os}}
    
    steps: 
      - name: Clone Repo
        uses: actions/checkout@v1
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }} 
          extensions: mysqli, mbstring
          tools: phpunit:5.7.27, composer
          
      - name: Shutdown Ubuntu MySQL
        run: sudo service mysql stop
        
      - name: Set up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '8.0'
          mysql database: 'testing_db'
          mysql root password: 123456
          mysql user: 'root' 
          mysql password: 123456
              
              
      - name: Install Dependencies
        run: composer install --prefer-source --no-interaction --no-dev
      - name: Create Storage Dir
        run: sudo mkdir /home/runner/work/framework/framework/src/storage
      - name: Create Sessions Dir
        run: sudo mkdir /home/runner/work/framework/framework/src/storage/sessions
      
      - name: Execute Tests
        run: phpunit
