name: Build PHP 7,8

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  test:
    runs-on: ${{ matrix.os }} 
    strategy: 
      fail-fast: true
      matrix: 
        os: [ ubuntu-latest ]
        php: [ 8.0, 7.4, 7.3, 7.2]
            
    name: PHP${{matrix.php}} - ${{matrix.os}}
    
    steps: 
      - name: Clone Repo
        uses: actions/checkout@v1
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }} 
          extensions: mysqli, mbstring
          tools: phpunit:8.5.13, composer
          
      - name: Shutdown Ubuntu MySQL
        run: sudo service mysql stop
        
      - name: Set up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '8.0'
          mysql database: 'testing_db'
          mysql root password: 123456
          mysql user: 'root' 
          mysql password: 123456
      
      - name: Start MySQL
        run: sudo service mysqld start
          
      - name: Wait for MySQL
        run: |
          while ! mysqladmin ping --host=127.0.0.1 --password=123456 --silent; do
            sleep 1
          done
          
      - name: Fix MySQL Login 
        run: mysql --user=root --password=123456 --execute="ALTER USER 'root'@'127.0.0.1' IDENTIFIED WITH mysql_native_password BY '123456';"
      
      - name: Install Dependencies
        run: composer install --prefer-dist --no-interaction --no-dev
        
      - name: Create DIR
        run: mkdir -m777 -p /home/runner/work/framework/framework/app/sto/sessions
        
      - name: Execute Tests
        run: phpunit -v
      
      - name: CodeCov
        uses: codecov/codecov-action@v1
        
      - name: SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
        
