name: Build PHP 7,8

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  test:
    runs-on: ${{ matrix.os }} 
    services: 
      mysql:
        image: mysql:8.0.26
        env:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: testing_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: 123456
        ports:
          - 33306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    strategy: 
      fail-fast: true
      matrix: 
        os: [ ubuntu-latest ]
        php: [ 8.0, 7.4, 7.3, 7.2]
            
    name: PHP${{matrix.php}} - ${{matrix.os}}
    
    steps: 
      - name: Clone Repo
        uses: actions/checkout@v1
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }} 
          extensions: mysqli, mbstring
          tools: phpunit:8.5.13, composer
          
      - name: Start MySQL
        run: |
          sudo systemctl start mysql.service
          while ! mysqladmin ping --host=127.0.0.1 --password=123456 --silent; do
            sleep 1
          done
          
      - name: Install Dependencies
        run: composer install --prefer-dist --no-interaction --no-dev
        
      - name: Create DIR
        run: mkdir -m777 -p /home/runner/work/framework/framework/app/sto/sessions
        
      - name: Execute Tests
        run: phpunit -v
      
      - name: CodeCov
        uses: codecov/codecov-action@v1
        
      - name: SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
        
